name: Build Application
on: [push]  # запускать при каждом пуше

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate venv and install dependencies
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Build with pyside6-deploy
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source .venv/Scripts/activate
          else
            source .venv/bin/activate
          fi
          pyside6-deploy mainwindow.py
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-${{ matrix.os }}
          path: ./deployment/   # путь к собранному бинарнику (зависит от конфига pyside6-deploy)
