name: Build Application
on: [push] # Запускать при каждом пуше

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Стабильная версия
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyside6-deploy # Или другие инструменты сборки
      - name: Build with Nuitka
        run: |
          python -m pyside6-deploy main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-${{ matrix.os }}
          path: ./deployment/ # Путь к собранному файлу
